export type User = {
    id: string;
    email: string;
    bio?: string;
    picture?: string;
    full_name?: string;
    username?: string;
    birthday?: Date;
    language?: string;
    primary_country_id?: string;
    primary_country_name?: string;
    phone?: string;
    twitter?: string;
    instagram?: string;
    website?: string;
    dark_mode?: string;
    text_notifications?: string;
    email_notifications?: string;
    created?: Date;
    updated?: Date;
    deleted?: Date;
};
